# Dependencies
markdown:         redcarpet
highlighter:      pygments

exclude: ['YEAR-MM-DD-example-content.md']

# Permalinks
permalink: blog/:year/:month/:day/:title/

# Portfolio Setup
collections:
  projects:
    output: true

# Setup
title:            'Brian Chuk'
tagline:          'A personal website'
description:      'A personal website of Brian Chuk'
url:              http://devchuk.github.io/devchuk2
baseurl:          /devchuk2/

author:
  name:           'Brian Chuk'
  url:            https://twitter.com/devchuk

paginate: 1
paginate_path: "blog/page:num"
excerpt_separator: <!---excerpt-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/devChuk/devchuk2